apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastmusik
  labels:
    {{- include "fastmusik.labels" . | nindent 4 }}
    app.kubernetes.io/component: fastmusik
spec:
  replicas: {{ .Values.fastmusik.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: fastmusik
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: fastmusik
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: fastmusik
          image: {{ .Values.fastmusik.image }}:{{ .Values.tag }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            periodSeconds: 1
            httpGet:
              path: /
              port: http
          readinessProbe:
            periodSeconds: 1
            httpGet:
              path: /
              port: http