apiVersion: v1
kind: Secret
metadata:
  name: hosts
  labels:
    app.kubernetes.io/component: hosts
    {{- include "client.labels" . | nindent 4}}
type: Opaque
data:
  api_gateway_host: {{ .Values.apiGatewayHost | b64enc }}